version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: berenjkade_db
    environment:
      POSTGRES_DB: berenjkade
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  